project:
  type: book

book:
  title: "Economic Reports"
  author: "Renato Vargas"
  date: "7/2/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - reports/0001-adapting-to-adversity.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



